#
# Copyright Hiemanshu Sharma <mail@theindiangeek.in>
#

USE_CAMERA_STUB := false

USE_PROPRIETARY_AUDIO_EXTENSIONS := false

TARGET_NO_RADIOIMAGE := true

DEVICE_PACKAGE_OVERLAYS += $(LOCAL_PATH)/overlay

TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := true
TARGET_ARCH_VARIANT := x86-atom
TARGET_CPU_ABI := x86
TARGET_CPU_SMP := true
TARGET_ARCH := x86
TARGET_PRELINK_MODULE := false
TARGET_HAS_THIRD_PARTY_APPS := true
TARGET_TOOLS_PREFIX := prebuilts/gcc/linux-x86/x86/i686-android-linux-4.4.3/bin/i686-android-linux-

BOARD_USES_TSLIB := false
BOARD_GPU_DRIVERS := i915
BOARD_GPS_HARDWARE := huawei
BOARD_USES_KBDSENSOR := true
BOARD_USES_DRM := true

BOARD_KERNEL_CMDLINE += video=LVDS-1:d video=1366x768 i915.modeset=1

BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_KERNEL_SOURCE :=
TARGET_KERNEL_CONFIG :=

BOARD_HAS_NO_RECOVERY := true
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 536870912 
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1073741824
BOARD_FLASH_BLOCK_SIZE := 4096

include $(GENERIC_X86_CONFIG_MK)
